Login
HAL-OSAKA-IT/game_collect pull request #20
Opened 2023-12-20 10:02 UTC by jmn04

2023-12-20 15:29 UTC, Toshiki428 requested changes
修正してほしい部分が数点あったので確認お願いします！

2023-12-20 15:29 UTC, Toshiki428 commented on member/login.php
> +            <h2>新規会員登録</h2>
画像は「新規会員登録」でしたが、
「会員の方」と同じレベルのタイトルなので「非会員の方」に変更をお願いします！

また、`h3`への変更をお願いします！

2023-12-20 15:29 UTC, Toshiki428 commented on member/login.php
> +    <h1>ログイン</h1>
headerのロゴ画像が`h1`になるので、ここは`h2`に修正お願いします！

2023-12-20 15:29 UTC, Toshiki428 commented on member/login.php
> +            <h2>会員の方</h2>
上と同様の理由で、ここは`h3`に修正をお願いします！

2023-12-20 15:29 UTC, Toshiki428 commented on member/login.php
> +            $_SESSION['name'] = $result['name'];
Sessionに`name`を保存すると、今後、会員情報変更機能を追加した時にSessionをいじる必要があるので、会員IDを保存しようと思います！
なので、`$_SESSION['member_id'] = $result['id'];`に変更をお願いします！

2023-12-20 15:29 UTC, Toshiki428 commented on member/login.php
> +================================================================================ */
セッションチェック機能までありがとうございます！
ここの処理については、これを参考に後ほど実装しようと思います。

なので今回のマージ部分からは消してしまって大丈夫です！

2023-12-20 15:29 UTC, Toshiki428 commented on member/login.php
> +        $result = $stmt -> fetch(PDO::FETCH_ASSOC);
`PDO::FETCH_ASSOC`はfunction.phpのdb_connect()で定義しているため、書かなくて大丈夫なはずです！

2023-12-20 21:33 UTC, jmn04 commented
login.phpのみ変更済みです。
scssはまだ変更が完了していません。

2023-12-20 23:25 UTC, Toshiki428 commented
承知しました！

修正したらまた連絡をお願いします！

2023-12-21 14:28 UTC, jmn04 commented
login.phpにおいて、パスワード表示非表示切り替え機能を追加しました。
scssにおいては、変更レビューの反映に加えて、上記機能実装に伴い一部修正しています。

2023-12-22 01:42 UTC, Toshiki428 commented
修正確認しました！

いきなりmainブランチにやると、登録機能と合わせるときに困る可能性があるので、
一旦memberブランチにマージすることにします！
この作業はこちらでやるので、ここからはゲーム制作の準備を進めてください！

2023-12-22 01:45 UTC, closed without merging